BEGIN TRANSACTION;

DROP TABLE IF EXISTS `TBL_PROJECT`;
CREATE TABLE IF NOT EXISTS `TBL_PROJECT` (
	`PK_id`	INTEGER NOT NULL,
	`TXT_title`	TEXT NOT NULL UNIQUE,
	`REAL_projectPrice`	REAL NOT NULL,
	`REAL_projectDeposite`	REAL NOT NULL,
	PRIMARY KEY(`PK_id`)
);
DROP TABLE IF EXISTS `TBL_GUEST`;
CREATE TABLE IF NOT EXISTS `TBL_GUEST` (
	`PK_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`ID_project`	INTEGER,
	`TXT_guestName`	TEXT NOT NULL,
	FOREIGN KEY(`ID_project`) REFERENCES `TBL_PROJECT`(`PK_id`) ON DELETE CASCADE,
	CONSTRAINT name_unique UNIQUE(`TXT_guestName`, `ID_project`)
	
);
DROP TABLE IF EXISTS `TBL_FOOD`;
CREATE TABLE IF NOT EXISTS `TBL_FOOD` (
	`FK_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`INT_nights`	INTEGER NOT NULL,
	`ID_guest`	INTEGER,
	`ID_project`	INTEGER,
	FOREIGN KEY(`ID_project`) REFERENCES `TBL_PROJECT`(`PK_id`) ON DELETE CASCADE,
	FOREIGN KEY(`ID_guest`) REFERENCES `TBL_GUEST`(`PK_id`) ON DELETE CASCADE,
	CONSTRAINT name_unique UNIQUE(`ID_guest`, `ID_project`)
);
DROP TABLE IF EXISTS `TBL_DRINKS`;
CREATE TABLE IF NOT EXISTS `TBL_DRINKS` (
	`FK_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`INT_nights`	INTEGER NOT NULL,
	`ID_guest`	INTEGER,
	`ID_project`	INTEGER,
	FOREIGN KEY(`ID_project`) REFERENCES `TBL_PROJECT`(`PK_id`) ON DELETE CASCADE,
	FOREIGN KEY(`ID_guest`) REFERENCES `TBL_GUEST`(`PK_id`) ON DELETE CASCADE,
	CONSTRAINT name_unique UNIQUE(`ID_guest`, `ID_project`)
);
DROP TABLE IF EXISTS `TBL_OTHEREXPENSE`;
CREATE TABLE IF NOT EXISTS `TBL_OTHEREXPENSE` (
	`FK_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`REAL_spend`	real,
	`TXT_reason`	TEXT,
	`TXT_when`	TEXT,
	`ID_guest`	INTEGER,
	`ID_project`	INTEGER,
	FOREIGN KEY(`ID_project`) REFERENCES `TBL_PROJECT`(`PK_id`) ON DELETE CASCADE,
	FOREIGN KEY(`ID_guest`) REFERENCES `TBL_GUEST`(`PK_id`) ON DELETE CASCADE
);

DROP TABLE IF EXISTS `TBL_STAY`;
CREATE TABLE IF NOT EXISTS `TBL_STAY` (
	`FK_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`INT_nights`	INTEGER,
	`ID_guest`	INTEGER,
	`ID_project`	INTEGER,
	FOREIGN KEY(`ID_project`) REFERENCES `TBL_PROJECT`(`PK_id`) ON DELETE CASCADE,
	FOREIGN KEY(`ID_guest`) REFERENCES `TBL_GUEST`(`PK_id`) ON DELETE CASCADE,
	CONSTRAINT name_unique UNIQUE(`ID_guest`, `ID_project`)
);

DROP TABLE IF EXISTS `TBL_PREPAID`;
CREATE TABLE IF NOT EXISTS `TBL_PREPAID` (
	`FK_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`REAL_prepaid`	REAL,
	`ID_guest`	INTEGER,
	`ID_project`	INTEGER,
	FOREIGN KEY(`ID_project`) REFERENCES `TBL_PROJECT`(`PK_id`) ON DELETE CASCADE,
	FOREIGN KEY(`ID_guest`) REFERENCES `TBL_GUEST`(`PK_id`) ON DELETE CASCADE,
	CONSTRAINT name_unique UNIQUE(`ID_guest`, `ID_project`)
);

DROP TABLE IF EXISTS `TBL_FOODEXPENSE`;
CREATE TABLE IF NOT EXISTS `TBL_FOODEXPENSE` (
	`FK_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`REAL_spend`	real,
	`TXT_reason`	TEXT,
	`TXT_when`	TEXT,
	`ID_guest`	INTEGER,
	`ID_project`	INTEGER,
	FOREIGN KEY(`ID_project`) REFERENCES `TBL_PROJECT`(`PK_id`) ON DELETE CASCADE,
	FOREIGN KEY(`ID_guest`) REFERENCES `TBL_GUEST`(`PK_id`) ON DELETE CASCADE
);

DROP TABLE IF EXISTS `TBL_DRINKEXPENSE`;
CREATE TABLE IF NOT EXISTS `TBL_DRINKEXPENSE` (
	`FK_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`REAL_spend`	real,
	`TXT_reason`	TEXT,
	`TXT_when`	TEXT,
	`ID_guest`	INTEGER,
	`ID_project`	INTEGER,
	FOREIGN KEY(`ID_project`) REFERENCES `TBL_PROJECT`(`PK_id`) ON DELETE CASCADE,
	FOREIGN KEY(`ID_guest`) REFERENCES `TBL_GUEST`(`PK_id`) ON DELETE CASCADE
);
COMMIT;