BEGIN TRANSACTION;

DROP TABLE IF EXISTS `TBL_HOUSE`;
CREATE TABLE IF NOT EXISTS `TBL_HOUSE` (
	`PK_id`	INTEGER NOT NULL,
	`TXT_title`	TEXT NOT NULL UNIQUE,
	`REAL_price`	REAL NOT NULL,
	`REAL_deposite`	REAL NOT NULL,
	PRIMARY KEY(`PK_id`)
);
DROP TABLE IF EXISTS `TBL_GUEST`;
CREATE TABLE IF NOT EXISTS `TBL_GUEST` (
	`PK_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`ID_house`	INTEGER,
	`TXT_name`	TEXT NOT NULL,
	FOREIGN KEY(`ID_house`) REFERENCES `TBL_HOUSE`(`PK_id`) ON DELETE CASCADE,
	CONSTRAINT name_unique UNIQUE(`TXT_name`, `ID_house`)
	
);
DROP TABLE IF EXISTS `TBL_FOOD`;
CREATE TABLE IF NOT EXISTS `TBL_FOOD` (
	`FK_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`INT_nights`	INTEGER NOT NULL,
	`ID_guest`	INTEGER,
	`ID_house`	INTEGER,
	FOREIGN KEY(`ID_house`) REFERENCES `TBL_HOUSE`(`PK_id`) ON DELETE CASCADE,
	FOREIGN KEY(`ID_guest`) REFERENCES `TBL_GUEST`(`PK_id`) ON DELETE CASCADE,
	CONSTRAINT name_unique UNIQUE(`ID_guest`, `ID_house`)
);
DROP TABLE IF EXISTS `TBL_DRINKS`;
CREATE TABLE IF NOT EXISTS `TBL_DRINKS` (
	`FK_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`INT_nights`	INTEGER NOT NULL,
	`ID_guest`	INTEGER,
	`ID_house`	INTEGER,
	FOREIGN KEY(`ID_house`) REFERENCES `TBL_HOUSE`(`PK_id`) ON DELETE CASCADE,
	FOREIGN KEY(`ID_guest`) REFERENCES `TBL_GUEST`(`PK_id`) ON DELETE CASCADE,
	CONSTRAINT name_unique UNIQUE(`ID_guest`, `ID_house`)
);
DROP TABLE IF EXISTS `TBL_EXPENSE`;
CREATE TABLE IF NOT EXISTS `TBL_EXPENSE` (
	`FK_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`REAL_spend`	real,
	`TXT_reason`	TEXT,
	`TXT_when`	TEXT,
	`ID_guest`	INTEGER,
	`ID_house`	INTEGER,
	FOREIGN KEY(`ID_house`) REFERENCES `TBL_HOUSE`(`PK_id`) ON DELETE CASCADE,
	FOREIGN KEY(`ID_guest`) REFERENCES `TBL_GUEST`(`PK_id`) ON DELETE CASCADE
);

DROP TABLE IF EXISTS `TBL_STAY`;
CREATE TABLE IF NOT EXISTS `TBL_STAY` (
	`FK_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`INT_nights`	INTEGER,
	`ID_guest`	INTEGER,
	`ID_house`	INTEGER,
	FOREIGN KEY(`ID_house`) REFERENCES `TBL_HOUSE`(`PK_id`) ON DELETE CASCADE,
	FOREIGN KEY(`ID_guest`) REFERENCES `TBL_GUEST`(`PK_id`) ON DELETE CASCADE,
	CONSTRAINT name_unique UNIQUE(`ID_guest`, `ID_house`)
);

DROP TABLE IF EXISTS `TBL_PREPAID`;
CREATE TABLE IF NOT EXISTS `TBL_PREPAID` (
	`FK_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`REAL_prepaid`	REAL,
	`ID_guest`	INTEGER,
	`ID_house`	INTEGER,
	FOREIGN KEY(`ID_house`) REFERENCES `TBL_HOUSE`(`PK_id`) ON DELETE CASCADE,
	FOREIGN KEY(`ID_guest`) REFERENCES `TBL_GUEST`(`PK_id`) ON DELETE CASCADE,
	CONSTRAINT name_unique UNIQUE(`ID_guest`, `ID_house`)
);
COMMIT;